services:
  db:
    image: postgres:15
    restart: always
    container_name: suspend_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: suspend_backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_ENV: development
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: suspend_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_FRONTEND_PROD: ${NEXT_PUBLIC_FRONTEND_PROD}
      NODE_ENV: production
    command: npm run build
